import type { NextPage } from 'next';
import Head from 'next/head';
import About from '../components/About';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Work from '../components/Work';

const Home: NextPage = () => {
  return (
    <div className="h-screen overflow-scroll z-0 snap-y snap-mandatory text-white" style={{ backgroundColor: 'rgb(17, 24, 39)' }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <About />
      <Work />
    </div>
  )
}

export default Home;
